services:
  # Proxy Server
  - type: web
    name: gynacology-proxy
    env: node
    buildCommand: npm install
    startCommand: node proxy-server.js
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

  # React App
  - type: web
    name: gynacology-app
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      npm install -g serve
      serve -s build -l $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: https://gynacology-proxy.onrender.com/api
      - key: PORT
        value: 3000
